import type { Metadata } from "next";
import {
  Fredoka,
  Geist,
  Geist_Mono,
  Poppins,
  Parisienne,
  The_Nautigal,
  Lobster,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { LoadingProvider } from "@/hooks/use-loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const parisienne = Parisienne({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-parisienne",
});

const theNautigal = The_Nautigal({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-the-nautigal",
});

const lobster = Lobster({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-lobster",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${fredoka.variable} ${parisienne.variable} ${theNautigal.variable} ${lobster.variable} antialiased`}>
        <Toaster />
        <LoadingProvider>{children}</LoadingProvider>
      </body>
    </html>
  );
}
